title: 'Analyse et sélection des titres'
author: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1721067501
blueprint: category
localizations:
  anglais:
    title: 'Analysis and stock selection'
    slug: analysis-and-stock-selection
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1721068838
