title: 'Conjoncture politique et économique'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1721067672
blueprint: category
localizations:
  anglais:
    title: 'Political and economic circumstances'
    content: ''
    slug: political-and-economic-circumstances
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1721068877
