title: 'Construction et gestion de portefeuille'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1721067736
blueprint: category
localizations:
  anglais:
    title: 'Portfolio construction and management'
    slug: portfolio-construction-and-management
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1721069000
