title: 'Cycles économiques'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1721068645
blueprint: category
localizations:
  anglais:
    title: 'Economic cycles'
    slug: economic-cycles
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1721069029
