title: 'Psychologie de l’investisseur'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1721069155
blueprint: category
localizations:
  anglais:
    title: 'Investor psychology'
    slug: investor-psychology
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1721069182
