title: 'Stratégie d’investissement'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1721069220
blueprint: category
localizations:
  anglais:
    title: 'Investment strategy'
    slug: investment-strategy
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1721069253
