title: 'Gestion privée (Croissance)'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1722870577
blueprint: variantes_portefeuille
localizations:
  anglais:
    title: 'Private Management (Growth)'
    slug: cote-100-croissance
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1722281109
