title: 'Gestion privée (Valeur)'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1722281286
blueprint: variantes_portefeuille
localizations:
  anglais:
    title: 'Private Management (Value)'
    slug: gestion-privee-valeur
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1722281264
