title: 'Fonds COTE 100 Revenu'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1722887350
blueprint: variantes_portefeuille
localizations:
  anglais:
    title: 'COTE 100 Revenue Funds'
    slug: revenu
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1722887372
