title: 'Acquisition potentielle'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1722875641
blueprint: statut_portefeuille
localizations:
  anglais:
    title: 'Potential acquisition'
    slug: acquisition-potentielle
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1722875655
