title: 'En portefeuille'
updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
updated_at: 1722875543
blueprint: statut_portefeuille
localizations:
  anglais:
    title: 'In portfolio'
    slug: en-portefeuille
    updated_by: 9c55616c-7340-47e9-bc83-f0bc3da40785
    updated_at: 1722875587
